server:
  port: 8888
spring:
  datasource:
    username: root
    password: Qydx123456.
    url: jdbc:mysql://223.247.214.249:3306/qydx?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
  redis:
    database: 0
    host: 223.247.214.249
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qydx.hmdj
upload:
  #filePath: d:/
  filePath: /zks/phonenumbers.d/